### ISSUE TITLE
Document does not have a meta description

### ISSUE THREAD

**Issue by Abdul-k1** [ebunedy/gridlayout#1]
Hello Ebune, i analysed your website using Lighthouse and i discovered that the "Document does not have a meta description".

<img width="598" alt="meta image" src="https://user-images.githubusercontent.com/14153036/185132410-ede9aac6-7dfa-471c-8b3f-89f2406eedbd.png">

Should i go ahead and fix this?

**Comment by ebunedy** [comment]
You can go ahead

**Comment by Abdul-k1** [comment]
Thanks sir..done already

**Comment by ebunedy** [comment]
thanks
